novel:
  file:
    endpoint: ${OSS_ENDPOINT:}
    key-id: ${OSS_KEY_ID:}
    key-secret: ${OSS_KEY_SECRET:}
    bucket-name: ${OSS_BUCKET_NAME:}
    file-host: ${OSS_FILE_HOST:pic}
    web-url: ${OSS_WEB_URL:}
