spring:
  config:
    import: classpath:application-common.yml
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 3000ms

logging:
  level:
    root: info
    com.java2nb: info

content:
  save:
    storage: db
    path: /var/lib/novel-plus/books

http:
  proxy:
    enabled: false
    ip: 127.0.0.1
    port: 80
