java2nb:
  uploadPath: /var/pic/
  username: ${NOVEL_ADMIN_DEMO_USERNAME:}
  password: ${NOVEL_ADMIN_DEMO_PASSWORD:}
logging:
  level:
    root: info
    com.java2nb: debug
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: test123456
    # 连接超时时间（毫秒）
    timeout: 10000


